services:
  - type: web
    name: igrid-project-management-dashboard
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENABLE_NGROK
        value: "false"
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@igridlab.edu.in
      - key: ADMIN_DEFAULT_PASSWORD
        value: Admin@123
